include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods
    # - non-nullable
  errors:
    unawaited_futures: ignore
    unused_local_variable: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"