include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    unawaited_futures: ignore
    unused_local_variable: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"