name: imes
description: A new IMES application.

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+1

environment:
  sdk: ">=2.10.4 <2.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_cupertino_localizations: ^1.0.1

  chopper: ^2.4.1

  octo_image: ^0.3.0
  cached_network_image: ^2.5.0

  device_info: ^1.0.0

  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_storage: ^7.0.0

  provider: ^4.0.4
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.12.3
  json_annotation: ^3.0.1
  freezed_annotation: ^0.12.0

  observable: ^0.23.0
  flutter_secure_storage: ^3.3.1+1
  flutter_state_notifier: ^0.6.1

  bubble: ^1.2.1
  photo_view: ^0.10.3
  better_player: ^0.0.61
  pin_code_text_field: ^1.7.1
  flutter_slidable: ^0.5.4
  flutter_typeahead: ^2.0.0
  mask_text_input_formatter: ^1.2.0

  permission_handler: ^5.0.1+1

  hive: ^1.5.0-pre
  hive_flutter: ^0.3.1

  timeago: ^2.0.28
  flutter_linkify: ^4.0.2

  share: ^2.0.1
  url_launcher: ^6.0.3
  path_provider: ^1.6.28
  image_picker: ^0.6.7+22
  shared_preferences: ^0.5.12

  validators: ^2.0.1

  sizer: ^1.1.8

  flutter_svg: ^0.19.3

  infinite_scroll_pagination: ^2.3.0

  # flutter_flipperkit: ^0.0.24

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  freezed: ^0.12.1
  json_serializable: ^3.2.5

  hive_generator: ^0.8.2
  chopper_generator: ^2.4.0

  pedantic: ^1.9.2
  test: ^1.15.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/res/
    - assets/drawable/
    - assets/guide/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
