- name: Flutter action
  uses: subosito/flutter-action@v1.4.0
  with:
    # The Flutter version to make available on the path
    flutter-version: # optional
    # The Flutter build release channel
    channel: # optional, default is stable
